Repository humphd/my-photohub, pull requests merged in 2022-11, with the labels that each got.

#17 Move Cloudflare Workers instructions
  CONTRIBUTING.md
  worker/index.js
Labels: documentation

#25 added linting and prop validation for react functional components
  .eslintrc.js
  package-lock.json
  package.json
  src/AuthDialog.js
  src/NavigationBar.js
  src/UploadInterface.js
Labels: enhancement

#24 Configure prettier for this project.
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  github-upload.js
  package-lock.json
  package.json
  src/AuthDialog.js
  src/NavigationBar.js
  src/UploadInterface.js
  src/gallery.css
  src/gallery.html
  src/gallery.js
  worker/functions/response.js
  worker/index.test.js
Labels: enhancement

#27 fix bug, closes #26
  src/NavigationBar.js
Labels: bug
